### ISSUE TITLE
TODOs before open-source launch

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#262]
- [x] write quality docs and example apps https://github.com/flojoy-io/docs/issues/7
- [x] migrate nodes and apps to their own dedicated repos https://github.com/flojoy-io/studio/issues/251
- [x] #265
- [x] #272
- [x] mock device instrumentation data for apps running in the cloud https://github.com/flojoy-io/studio/issues/258
- [x] test and document running flojoy "on the edge" on a rasberry pi https://github.com/flojoy-io/docs/issues/7
- [x] benchmark a set of job run times and add to CI in case of slowdown regressions https://github.com/flojoy-io/studio/issues/137
- [x] add mixpanel, sentry, and redis logs telemetry: https://github.com/flojoy-io/studio/issues/277
