### ISSUE TITLE
visual cypress tests

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#263]
# Unit tests

- [x] https://github.com/flojoy-io/studio/issues/260
- [x] https://github.com/flojoy-io/studio/issues/224
- [x] https://github.com/flojoy-io/studio/issues/222
- [x] https://github.com/flojoy-io/studio/issues/178
- [x] https://github.com/flojoy-io/studio/issues/307
- [ ] connecting nodes with wires

# e2e / regression tests

- [x] #317
- [ ] #318
- [ ] deleting multiple nodes at once
- [ ] creating nodes
- [ ] loading an app from disk
- [ ] saving an app 
- [ ] add a CTRL panel widget
- [ ] remove a CTRL panel widget
- [ ] permutations for the most popular windows and mac OS's

**Comment by jackparmer** [comment]
going to use reflect.run for these e2e tests

https://flowjoy.slack.com/archives/C03KH05RZLK/p1684288515083299

**Comment by jackparmer** [comment]
@mehedihasansabbir220 please use this Applitools + cypress test that @itsjoeoui created as a reference:
https://github.com/flojoy-io/studio/blob/main/cypress/e2e/01_main_page.cy.ts

The please update the cypress tests here that have been commented out by turning them into visual tests with cypress+Applitools:
https://github.com/flojoy-io/studio/tree/main/cypress/e2e

Finally, please starting adding  _**new**_ visual tests with cypress+Applitools to this folder:
https://github.com/flojoy-io/studio/tree/main/cypress/e2e
You can use some of the suggestions for new tests in this issue as a starting point.

**Comment by jackparmer** [comment]
closed via https://github.com/flojoy-io/studio/issues/626
