### ISSUE TITLE
[Epic] Paywall & test Electron installer

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#301]
We're going to make Electron's GUI installer a paid feature (see https://www.flojoy.io/#pricing).
Everyone using the Free tier will use the Unix/Windows/Mac CLI installer instead.

There's a number of open items to deliver this:
- [ ] Create a private `GUI` repo where we can post Electron build Releases
- [ ] Set up automated desktop testing of these releases, or at least a human QA/QE process
- [ ] Make sure we're registered as an Apple Developer 
- [x] Update the docs for CLI installation for Mac and Windows, and remove GUI installation

**Comment by trbritt** [comment]
It should be mentioned the currency of the $ on the pricing page, as the `.io` domain of the site does not give a clear indication of the base region of the company.
