### ISSUE TITLE
[VIZ] Time series streaming

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/studio#354]
The plotly React component sadly does not support streaming updates (eg, it repaints the entire chart on each data update - see https://github.com/plotly/react-plotly.js/issues/85#issuecomment-398399514)

When streaming from sensors, users will want silky-smooth, performant, and real-time animation updates - so we'll need another viz library for this. This dedicated time series React lib seems to fit the bill:
http://software.es.net/react-timeseries-charts/#/example/realtime

Incomplete list of steps to get this working:

- [ ] create a component like https://github.com/flojoy-io/studio/blob/main/src/feature/common/PlotlyComponent.tsx, but for "React Timeseries Charts"
- [ ] add this component to the controls manifest: https://github.com/flojoy-io/studio/blob/main/src/feature/controls_panel/manifest/CONTROLS_MANIFEST.ts
- [ ] create a "time series streaming" node in the `nodes` repo that forwards incremental TS data from prior nodes (eg, from an Arduino sensor, LabJack, etc). 
- [ ] It would nice to be able to support N data stream inputs (eg N lines on the same plot), so that you don't need to have 6 different plots for a set of 6 sensors.
- [ ] add a dedicated `time_series` `DataContainer` type. this will allow downstream nodes and frontier special processing. we can also enforce numpy's datetime64 as the x-axis type

**Comment by jackparmer** [comment]
More on creating custom nodes:
https://docs.flojoy.io/custom-nodes/creating-custom-node/#creating-custom-component--frontend-

**Comment by JeffDotPng** [comment]
`react-timeseries-charts` is unmaintained (last real commit on repo around 4 years ago), and it depends on React 16, going to have to find something else.
